-- Enable vector similarity search using pgvector
-- Part of Initiative 2.2: Closing the Data Gaps (Next-Gen CV)

-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add vector column for image embeddings (768 dimensions for Gemini embeddings)
ALTER TABLE photo_metadata
ADD COLUMN IF NOT EXISTS embedding vector(768);

-- Create index for vector similarity search (using HNSW for better performance)
CREATE INDEX IF NOT EXISTS idx_photo_metadata_embedding
ON photo_metadata
USING hnsw (embedding vector_cosine_ops);

-- Add comment explaining the column
COMMENT ON COLUMN photo_metadata.embedding IS
'768-dimensional embedding vector generated by Google Gemini for semantic similarity search';

-- Verify the change
SELECT
  column_name,
  data_type,
  is_nullable
FROM information_schema.columns
WHERE table_name = 'photo_metadata'
  AND column_name = 'embedding';

-- Create function to find similar photos
CREATE OR REPLACE FUNCTION find_similar_photos(
  query_image_key TEXT,
  match_count INT DEFAULT 12,
  match_threshold FLOAT DEFAULT 0.7
)
RETURNS TABLE (
  image_key TEXT,
  thumbnail_url TEXT,
  sport_type TEXT,
  play_type TEXT,
  similarity FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    pm.image_key,
    pm.thumbnail_url,
    pm.sport_type,
    pm.play_type,
    1 - (pm.embedding <=> (SELECT embedding FROM photo_metadata WHERE image_key = query_image_key)) AS similarity
  FROM photo_metadata pm
  WHERE pm.image_key != query_image_key
    AND pm.embedding IS NOT NULL
    AND 1 - (pm.embedding <=> (SELECT embedding FROM photo_metadata WHERE image_key = query_image_key)) > match_threshold
  ORDER BY pm.embedding <=> (SELECT embedding FROM photo_metadata WHERE image_key = query_image_key)
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION find_similar_photos IS
'Find photos similar to a given image based on vector embeddings. Returns photos sorted by cosine similarity.';
